spring:
  datasource:
    url: ${TTRL_DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${TTRL_DB_USER:postgres}
    password: ${TTRL_DB_PASS:postgres}
    driverClassName: org.postgresql.Driver
    hikari:
      connectionTimeout: 1000

ttrl:
  dao:
    database: postgres
    type: jdbc
